src/output/plugins/OSXOutputPlugin.cxx
In e068d62 I added code that zeros the remainder of the output buffer
if there are not enough input frames available. I have now learned
that we can signal to the caller of the render callback how much data
is in the output buffers. In practice, the input buffer is so large
that it does not matter so much how we handle input buffer underruns,
but I suppose that saying 'there is no data' is better than 'here is
some silence for you'.
=> output/osx: remove incorrect memset behavior

AUTHORS, Makefile.am, NEWS, src/mixer/MixerList.hxx, src/mixer/plugins/OSXMixerPlugin.cxx, src/output/plugins/OSXOutputPlugin.cxx, src/output/plugins/OSXOutputPlugin.hxx
Following up on https://github.com/MusicPlayerDaemon/MPD/pull/100
=> OS X mixer (master)

src/decoder/plugins/GmeDecoderPlugin.cxx
This is for issue #115  I'll be honest, my C++ skills are pretty lacking, I hope this is up-to-snuff! I saw there were some Path classes in the MPD codebase, but I wasn't sure how to properly use them, so I'm just using `std::string`.
The `gme_load_m3u` function seems to be really flexible/tolerant with what you throw at it, I tried loading several m3u files, cat-ing /dev/urandom into m3u files (some a few bytes, some a few hundred megabytes), and missing m3u files. GME will report an error, but otherwise continue loading/playing songs.
I wasn't sure if MPD has any classes/mechanisms for finding a file while ignoring case, or if that's not a particularly large concern?
=> GME Plugin: try loading m3u sidecar files

src/output/plugins/OSXOutputPlugin.cxx
- Update the mixer to set on device property instead of audio unit property. When user choose "hardware" as mixer type, they will be able to change the hardware device volume instead of the software (AudioUnit) volume. 
- We don't use square root scale in volume calculation as previous code did. This will make the volume level in line with system volume meter --- That is, MPD will have the same percentage volume reading compared to System Setting (Either in "System Preference" or in "Audio Midi Setup" app)
=> enable macOS  to use Hardware Mixer

doc/user.rst
Add link to more recent libsidplayfp and correct URL pointing to libsidplay2.
=> user.rst: update and fix sidplay links

src/output/plugins/OSXOutputPlugin.cxx
the most notable bugs are 
1. osx_output_set_device_format should use the target asbd rather than AudioFormat. This is because asbd's sample rate calculation reflects the real dop target rate of the DAC, white AudioFormat's sample rate is the original DSD format rate.
2. the original code value the highest rate that's the multiple of the target rate. This cause DOP always have the wrong rate chosen. This is also not necessary for PCM playback --- MPD's goal is bit perfect, and it's meaningless to raise to two or four times the PCM sample rate.
3.  if sample_rate cannot be synchronized, the test for falling back to PCM is wrong. If the file format is in DSD format such fallback is necessary, whatever the params.dop setting is.
=> Fix various bugs in OS X DSD playback

doc/user.rst, src/input/plugins/CdioParanoiaInputPlugin.cxx
Please find pull request to allow the cdparanoia CD speed to be set similar to mplayer
=> Set cdrive speed hint for cdparanoia

doc/protocol.rst
Add `oneshot` to the argument list for `single` command
=> doc/protocol.rst: oneshot argument

src/db/meson.build, src/event/meson.build, src/input/meson.build, src/song/meson.build, src/storage/meson.build
I couldn't get MPD to build on macOS with MacPorts until I added these. I am not a Meson expert and I don't know if what I'm doing here makes sense.
=> Add meson dependencies

src/db/VHelper.cxx, src/decoder/plugins/AudiofileDecoderPlugin.cxx
Closes https://github.com/MusicPlayerDaemon/MPD/issues/456
=> Add missing include of stdlib.h.

doc/plugins.rst, src/mixer/plugins/PulseMixerPlugin.cxx
Closes GH-479.  I have added documentation, but no tests (I'd love to, but I wasn't sure where to add them or how to test)
=> mixer/pulse: Add a new 'scale' parameter to allow volumes above 100

src/command/DatabaseCommands.cxx, src/db/plugins/simple/SimpleDatabasePlugin.cxx, src/decoder/plugins/WavpackDecoderPlugin.cxx
Found with modernize-make-unique
=> [clang-tidy] use make_unique

src/pcm/Export.cxx
Found with -Wunreachable-code-break
=> remove unreachable code

src/Chrono.hxx, src/lib/dbus/AppendIter.hxx, src/thread/Mutex.hxx
=> remove extra semicolon

src/ReplayGainGlobal.cxx, src/ReplayGainInfo.cxx, src/command/PlayerCommands.cxx, src/decoder/Bridge.cxx, src/decoder/plugins/MadDecoderPlugin.cxx, src/decoder/plugins/OpusTags.cxx, src/encoder/plugins/LameEncoderPlugin.cxx, src/encoder/plugins/TwolameEncoderPlugin.cxx, src/encoder/plugins/VorbisEncoderPlugin.cxx, src/mixer/plugins/PulseMixerPlugin.cxx, src/mixer/plugins/SoftwareMixerPlugin.cxx, src/output/Source.cxx, src/pcm/Dsd2Pcm.cxx, src/pcm/FloatConvert.hxx, src/pcm/Mix.cxx, src/pcm/SoxrResampler.cxx, src/pcm/Volume.hxx, src/queue/PlaylistState.cxx
=> fix double promotions

src/output/plugins/sles/SlesOutputPlugin.cxx
Regression from 973c87b351b31961a51b6ea9afc4bea0872565ad
=> output/sles: fix invalid assert

doc/mpdconf.example, doc/plugins.rst, src/mixer/plugins/WasapiMixerPlugin.cxx, src/mixer/plugins/meson.build, src/output/Registry.cxx, src/output/plugins/WasapiOutputPlugin.cxx, src/output/plugins/WasapiOutputPlugin.hxx, src/output/plugins/meson.build, src/win32/Com.hxx, src/win32/ComHeapPtr.hxx, src/win32/ComPtr.hxx, src/win32/HResult.hxx, src/win32/WinEvent.hxx
Add WASAPI event output plugin with doc.
=> WIP: src/output: add wasapi output and mixer plugin

src/decoder/DecoderAPI.cxx, src/io/FileDescriptor.cxx
=> clang-tidy: use auto

src/storage/plugins/CurlStorage.cxx
Fixes https://github.com/MusicPlayerDaemon/MPD/issues/1043
The original base relative path was introduced due to an erroneous test where the URL started with three slashes: "https:///" instead of two, which led to implementing handling for such cases but broke the two slashes case.
This fix removes the base relative path handling because with two slashes the path is anyway always relative to the host (aka absolute URI, without host).
This reverts 216f62ea1468933f4a78f17885b27e37e1393d8c and part of 74b2fc7fdca9be13cbbe4cb52b2fab573b3cf82c
I've tested rescanning with both "music_directory" pointing at Webdav and also using "mpc mount".
=> Remove relative path handling which was not needed

doc/protocol.rst
=> fix typo in protocol.rst

doc/client.rst
Mention possibility to expose MPD password in `MPD_HOST`.
=> Add password use with MPD_HOST

src/RemoteTagCache.cxx, src/client/Subscribe.cxx, src/db/Count.cxx, src/db/DatabasePrint.cxx, src/db/plugins/simple/Directory.cxx, src/db/update/Walk.cxx, src/event/WinSelectBackend.cxx, src/input/plugins/CurlInputPlugin.cxx, src/input/plugins/QobuzClient.cxx, src/lib/curl/Form.cxx, src/neighbor/plugins/UdisksNeighborPlugin.cxx, src/output/Print.cxx, src/output/plugins/WasapiOutputPlugin.cxx, src/sticker/Print.cxx, src/tag/GenParseName.cxx
=> use structured binding declarations

meson_options.txt, src/db/plugins/upnp/ContentDirectoryService.cxx, src/lib/upnp/Action.hxx, src/lib/upnp/ContentDirectoryService.cxx, src/lib/upnp/Init.cxx, src/lib/upnp/UniqueIxml.hxx, src/lib/upnp/ixmlwrap.cxx, src/lib/upnp/ixmlwrap.hxx, src/lib/upnp/meson.build
libnpupnp is a C++ modification of libupnp.
I've had this patch locally. Might as well submit it.
=> Add npupnp support

android/AndroidManifest.xml, android/res/layout/settings.xml, android/res/values/strings.xml, android/src/Bridge.java, android/src/IMain.aidl, android/src/Main.java, android/src/Settings.java, src/Main.cxx
This pull request adds a check box to the Android app that gives the option of pausing MPD when Bluetooth or wired headphones are disconnected.
=> Android: add option to pause MPD when headphones disconnect

src/command/FileCommands.cxx, src/sticker/Database.cxx
=> Fix compile error on macOS 11.15.2 (introduced by commit 30e3ef4)

src/db/plugins/upnp/ContentDirectoryService.cxx
loop is wrong anyway. It's missing a break;
=> replace loop with find_if

src/db/plugins/upnp/Directory.cxx, src/decoder/Control.cxx, src/playlist/cue/CueParser.cxx
These should be equivalent anyway.
=> prevent use after move

python/build/libs.py
Signed-off-by: Shen-Ta Hsieh <ibmibmibm.tw@gmail.com>
=> python/build/libs.py: disable building libopenmpt cli

src/command/FileCommands.cxx, src/decoder/plugins/MadDecoderPlugin.cxx, src/decoder/plugins/SidplayDecoderPlugin.cxx, src/lib/icu/Util.cxx, src/lib/xiph/VorbisPicture.cxx, src/output/plugins/OSXOutputPlugin.cxx, src/tag/ApeLoader.cxx, src/tag/Id3Load.cxx
C arrays can be used with make_unique in C++17.
=> use auto with make_unique

src/net/AddressInfo.cxx
=> convert address_family_ranking to std::array

doc/user.rst
Update PCRE2 library
cf. https://bugs.debian.org/1000033
=> doc/user.rst: update build dependencies on Debian Bullseye

src/output/plugins/PipeWireOutputPlugin.cxx
=> use nullptr

src/archive/plugins/Iso9660ArchivePlugin.cxx, src/event/ServerSocket.cxx, src/event/SignalMonitor.cxx, src/lib/curl/Global.cxx, src/mixer/plugins/AlsaMixerPlugin.cxx, src/output/plugins/PipeWireOutputPlugin.cxx
=> add various nodiscard

src/decoder/plugins/AudiofileDecoderPlugin.cxx
=> use const references

src/Mapper.cxx, src/MusicBuffer.cxx, src/db/plugins/simple/Directory.cxx, src/db/plugins/upnp/UpnpDatabasePlugin.cxx, src/db/update/Queue.cxx, src/fs/AllocatedPath.cxx, src/fs/Path.cxx, src/lib/icu/CaseFold.cxx, src/lib/icu/Converter.cxx, src/lib/upnp/Discovery.cxx, src/player/Thread.cxx, src/playlist/plugins/ExtM3uPlaylistPlugin.cxx, src/protocol/ArgParser.cxx, src/song/DetachedSong.cxx, src/song/Filter.cxx, src/song/LightSong.cxx, src/sticker/Database.cxx, src/storage/CompositeStorage.cxx, src/util/UriUtil.cxx
=> return by braced init list

src/event/SignalMonitor.cxx, src/output/plugins/AlsaOutputPlugin.cxx, src/pcm/Dsd2Pcm.cxx, src/pcm/Dsd2Pcm.hxx, src/util/UriUtil.cxx
=> array conversions

src/encoder/plugins/FlacEncoderPlugin.cxx
This fixes a bug introduced in 87fa6bca where the FLAC encoder fails to initialize unless libFLAC is built with Ogg support. When libFLAC is built without Ogg support, FLAC__stream_encoder_set_ogg_serial_number unconditionally returns false.
=> encoder/flac: only set a serial number for oggflac

doc/protocol.rst, src/PlaylistSave.cxx, src/PlaylistSave.hxx, src/command/AllCommands.cxx, src/command/PlaylistCommands.cxx
by either replacing or appending to the existing list.
=> Added command store {NAME} {REPLACE} to save the player queue to an existing playlist

src/command/AllCommands.cxx, src/command/StorageCommands.cxx, src/command/StorageCommands.hxx, src/db/plugins/simple/SimpleDatabasePlugin.hxx
=> add precondition for mount/unmount in commands response

doc/plugins.rst
Result of the discussion: "Does the curl plugin actually pay attention to .curlrc?" #1648
=> Document curl plugin .netrc and .curlrc behavior

doc/plugins.rst, src/decoder/plugins/OpenmptDecoderPlugin.cxx
Here's a useful option for the openmpt plugin. Enjoy
=> openmpt: add at_end option

src/decoder/plugins/FluidsynthDecoderPlugin.cxx
=> Decoder/FluidSynth: Allow gain to be adjusted

doc/mpd.1.rst
This switch was introduced in ce77b148d927c3012d04f629266476c8ffeb183a
=> doc/mpd.1.rst: add documentation for --systemd

doc/protocol.rst
From https://github.com/MusicPlayerDaemon/MPD/discussions/1899 discussion.
=> doc/protocol.rst: mention song id lifetime

src/input/plugins/AlsaInputPlugin.cxx
Some ALSA capture devices can have very large buffers, holding 10 seconds or more audio. Using the maximum buffer size with such devices leads to unacceptably large, and unnecessary, latency. Also, some ALSA drivers (e.g. HDA Intel PCH) report an invalid maximum period size, and the period size that mpd calculates from the maximum buffer size results in "Invalid argument" error when applying the hw_params. Note that the "default" capture device on many cards includes the "dsnoop" plugin which imposes a buffer size of 16384 frames, so that "alsa://" works OK but "alsa://plughw" or "alsa://hw" both fail.
Limit the maximum buffer time for ALSA input devices to a more useable 2 seconds, thereby avoiding both the above problems.
=> input/plugins/Alsa: limit ALSA buffer time to 2 seconds maximum

.github/workflows/build_android.yml
This lives under a separate workflow so it can have different ignore paths.
=> android: Add github action

src/fs/Charset.cxx
=> fs: fix typo

android/app/src/main/AndroidManifest.xml, android/app/src/main/java/org/musicpd/AutomationReceiver.kt, android/app/src/main/java/org/musicpd/Main.java, android/app/src/main/java/org/musicpd/MainActivity.kt, android/app/src/main/java/org/musicpd/MainServiceClient.java, android/app/src/main/java/org/musicpd/Receiver.java, android/app/src/main/java/org/musicpd/ui/SettingsViewModel.kt
org.musicpd.action.StartService
org.musicpd.action.StopService
You can test these actions like:
adb shell am broadcast -a org.musicpd.action.StartService org.musicpd
Calling these from an app like tasker should allow for automation
Should fix #1290
=> android: Add intents for service start and stop

doc/user.rst
Add extra build deps libsystemd and libpipewire.
I believe this can be usefull on Debian bookworm.
=> Doc user debian build

doc/protocol.rst, src/song/Filter.cxx
The default case sensitivity is hard coded for each command. These operators allow to override this default case sensitivity.
=> Added explicitly case sensitive/insensitive filter operators.

NEWS, doc/protocol.rst, src/command/AllCommands.cxx, src/command/StickerCommands.cxx, src/command/StickerCommands.hxx
Prints all available stickertypes like tagtypes for tags.
=> Add command stickertypes

NEWS, doc/protocol.rst, src/command/AllCommands.cxx, src/command/StickerCommands.cxx, src/command/StickerCommands.hxx, src/sticker/Database.cxx, src/sticker/Database.hxx
Lists sticker names with their types and optionally filters by type
=> New command stickernamestypes

src/SongPrint.cxx, src/Stats.cxx, src/TagPrint.cxx, src/TimePrint.cxx, src/client/Idle.cxx, src/client/Response.cxx, src/command/AllCommands.cxx, src/command/DatabaseCommands.cxx, src/command/FileCommands.cxx, src/command/MessageCommands.cxx, src/command/OtherCommands.cxx, src/command/PartitionCommands.cxx, src/command/PlayerCommands.cxx, src/command/PlaylistCommands.cxx, src/command/QueueCommands.cxx, src/command/StorageCommands.cxx, src/command/TagCommands.cxx, src/db/Count.cxx, src/db/DatabasePrint.cxx, src/decoder/DecoderPrint.cxx, src/decoder/plugins/meson.build, src/ls.cxx, src/output/Print.cxx, src/queue/QueuePrint.cxx, src/sticker/Print.cxx
Fixes build with fmt-11.1.0
- https://github.com/fmtlib/fmt/issues/4304#issuecomment-2585356850
- #2173
=> lib/fmt: drop use of FMT_STRING
