src/command/QueueCommands.cxx

Previously the id was being returned only when a position wasn't
specified.

return id for "addid" with position

---

src/output/plugins/OSXOutputPlugin.cxx

Hi! The OS X output plugin creates about 15 deprecation warnings during compilation, and it also emits a deprecation warning at runtime. This change gets rid of the warning by using what appears to be the current APIs.
I am not an experienced OS X or C++ developer but I hope you will consider this change for review anyway. Thanks!

OSX output plugin: get rid of compile time and runtime deprecation warnings

---

doc/mpd.conf.5
doc/mpdconf.example
doc/user.xml
src/output/plugins/OSXOutputPlugin.cxx

Add the ability to pick output channels on multi-channel sound cards in OS X.

output/osx channel_map feature

---

src/output/plugins/OSXOutputPlugin.cxx

Closes https://bugs.musicpd.org/view.php?id=4537 .
Removed the 'cancel' function because it violates 'single producer,
single consumer'.

output/osx: wait-free render callback

---

AUTHORS
doc/user.xml
src/output/plugins/OSXOutputPlugin.cxx

Add sample rate synchronization, which ensures mpd play bit perfectly on OS X. User can enable this by setting sync_sample_rate to "true".
Add device hogging capability. This forbids other process interfere with selected user devices. User may enable this by setting "hog_device" to "true".
Kill the mutex, locks, extra buffer in original code. Now you'll see greater than 3X performance improvement.
Set the right buffer length for the device.
Fix an audio unit initialization problem. 
Code borrowed from the CMUS project. I am the author of cmus coreaudio output plugin. So I have full rights to redistribute the code. The coding style may be slightly different, but we can always polish/refactor it in another PR. 
@jacobvosmaer Please take a look.
@MaxKellermann please merge.

A lot of improvements to OS X output plugin

---

src/output/OutputPlugin.hxx
src/output/plugins/OSXOutputPlugin.cxx

This further optimize the performance. 
This is now working properly with a conditional variable bug being fixed (8bbfb5cda12e105460c1e2bf22066873ecc29b0f).

use osx_output_delay to wait until ring buffer is able to write

---

src/system/EventPipe.cxx

Current MPD head crashes on starting playback on macOS Sierra. On investigation this seems to be due to a typo in `EventPipe.cxx` attempting to use the read file descriptor as both R/W.
This patch fixes playback on my system.

Fix EventPipe file descriptors

---

Makefile.am
doc/mpdconf.example
src/mixer/MixerList.hxx
src/mixer/plugins/SndioMixerPlugin.cxx
src/output/plugins/SndioOutputPlugin.cxx
src/output/plugins/SndioOutputPlugin.hxx

Building on any unix with ``sin_size`` in ``sockaddr_in`` is broken.
I fix this not by using additional ``#ifdef``s, but by initializing the anonymous ``sockaddr_in`` with explicit field names. The ``sin_size`` field does not require initialization and is implicitly initialized to ``0``.

Add sndio mixer, fix building on BSD

---

src/decoder/plugins/GmeDecoderPlugin.cxx

GME starts all track indexes at zero, but the subtune prefixes start at one. This caused an off-by-one error with track titles.
It also turns out, if you load an NSFE file (which has embedded track titles), then attempt to load an M3U file, it causes GME to lose all information found in the NSFE file. This adds a check that the M3U file exists before attempting to load.

GME Plugin: fix track numbering, only load m3u when it exists

---

configure.ac
src/net/IPv4Address.hxx

This fixes a build issue on Haiku as it does have sin_len.
Tested on Linux as well.
For some reason AC_CHECK_MEMBER doesn't generate the proper define
in config.h.in, so I used AC_CHECK_MEMBERS.

configure.ac: autodetect sin_len member in struct sockaddr_in.

---

src/output/plugins/HaikuOutputPlugin.cxx

Convert the fill_buffer to a class method, to allow accessing the private method.
Also remove the leftover Wrapper stuff.

Haiku: fix build

---

src/db/plugins/upnp/Directory.cxx

According to http://www.upnp.org/schemas/av/didl-lite-v2.xsd the duration of a song can have fractions of seconds (quote from above url):
The format of the duration string is:
H+:MM:SS[.F+], or H+:MM:SS[.F0/F1]
Where:
+H              one or more digits to indicate elapsed hours,
MM              exactly 2 digits to indicate minutes (00 to 59),
SS              exactly 2 digits to indicate seconds (00 to 59),
F+              any number of digits (including no digits) to indicate fractions of seconds,
F0/F1   a fraction, with F0 and F1 at least one digit long,
and F0 < F1.
The string may be preceded by an optional + or - sign, and the
decimal point itself may be omitted if there are no fractional  seconds digits.
This patch enables to read durations in the first format, i.e. H+:MM:SS[.F+] …

db/upnp/Directory: improve parsing of duration

---

src/command/FileCommands.cxx

read_stream_art uses PRIu64 unconditionally with the Format method of a Respone instance to output a size_t typed value. If size_t is 32bit the output is garbeled. This patch uses offset_type and PRIoffset to make sure the format string and the type of the output value always match.

Fix for bogus output of the albumart command on 32bit platforms

---

NEWS
doc/user.xml
src/encoder/plugins/OpusEncoderPlugin.cxx

support for chaining streams to enable changing stream' metadata on the fly.
currently support is opt-in because lots of clients can't handle this properly yet.

opus stream chaining

---

src/output/plugins/OSXOutputPlugin.cxx

Includes the following:
- use system output device (the device used for notifications) in case configured in mpd.conf (before default device was used e.g. for sample rate synchronization if configured whereas system device was used for output)
- use AudioOutputUnitStop to implement Pause()
- fix sample rate synchronization for rates below the minimum rate available on the device (before maximum rate was used in these cases)
- Get initial sampling rate of the output device and reset it when we close the output
- Fix build with DSD disabled (this was introduced by the DoP implementation sent earlier)

Some improvements for OSX output plugin

---

src/output/plugins/OSXOutputPlugin.cxx

While working on a new Mac OS output plugin I found that Pause() was not reflected in Delay() function causing high CPU load. Apologies for the oversight in the first place...

Fix pause for OSX output plugin (delay one second)

---

doc/user.xml
src/output/plugins/OSXOutputPlugin.cxx

This PR will fix #271.
special thanks to @coroner21 who contributed a nice way to score hardware supported format in #292
Also, The DSD related code are all guarded with ENABLE_DSD  flag.

Enable OSX to set both hardware sample rate and bit depth 

---

src/thread/PosixCond.hxx

Some Audio plugin (such as ALSA, and soon CoreAudio) already support microsecond level buffer time. However, current interval less than 1000 microseconds will cause a bug that the code treated as 0 ms.

Support timed_wait in microseconds level

---

src/event/ServerSocket.cxx
src/net/SocketUtil.cxx

Quick fix to use fchmod for unix sockets to prevent TOCTTOU (TimeOfCheckToTimeOfUse).
Its better to set permissions before the socket is finally created.
Also it would be good to let the user decide which permissions to apply instead of hardcoding 0666.
Have this working on a local branch, maybe worth another PR?
Btw:
How about calling unlink() for a (maybe existing) socket in socket_bind_listen() or SocketDescriptor::Bind(), instead of ServerSocket::AddPath()?
So we would have creation and deletion together. No disadvantage in the current approach, its just a feeling.

Use fchmod instead of chmod for unix sockets to prevent TOCTTOU

---

Makefile.am
NEWS
doc/user.rst
src/Listen.cxx
src/config/Net.cxx
src/config/Net.hxx
src/output/plugins/httpd/HttpdOutputPlugin.cxx

Just a quick patch to enable unix sockets.
I did no checking for HAVE_UN since this is already done in AddPath.
"Works fine for me".
For now socket permissions are hardcoded to 0666 but I will create a PR tomorrow (or so) for adding support to set socket permissions in mpd.conf...

Add support for unix socket to HttpdOutputPlugin

---

doc/user.rst
src/decoder/plugins/SidplayDecoderPlugin.cxx

Some SID tunes - eg Commodore Basic Demos from HVSC - require basic and/or kernal rom to play but dumps are not embedded in libsidplayfp - please note https://sourceforge.net/p/sidplay-residfp/news/2013/01/released-libsidplayfp-100beta1/ 
Patch adds kernal and basic configuration parameters to load corresponding rom dumps.

decoder/sidplay: support basic and kernal rom (libsidplayfp)

---

src/event/ServerSocket.cxx
src/net/SocketUtil.cxx
src/net/SocketUtil.hxx

Call fchmod() first to prevent TOCTTOU.
Then apply permissions using hmod().
This is related to issue #337

fixed setting unix socket permissions

---

src/decoder/plugins/WavpackDecoderPlugin.cxx

decoder/wavpack: fix warning 'unused variable is_dsd' when compiled with option --enable-dsd=no

decoder/wavpack: fix warning 'unused variable is_dsd' (--enable-dsd=no)

---

src/decoder/plugins/SidplayDecoderPlugin.cxx

decoder/sidplay: fix typo to avoid meson linker error (libsidplayfp)

---

doc/user.rst
src/tag/Id3Scan.cxx
src/tag/Names.c
src/tag/Type.h

Maps ID3Tag TPUB to the new Music Player daemon tag Label. According to ID3.org, TPUB is used for label or publisher information. Basically, a label is a company that sells music. Not very exciting so far. But in the field of electronic music there are specialized labels, eg. Rephlex or Central Processing Unit with its own unique style. Furthermore, artists in the field of electronic (dance) music like to use dozens or even more pseudonyms, but often remain loyal to a few labels. The new tag label can therefore simplify the search for the desired music.

tag: new tag Label

---

doc/user.rst

Fix typo in new build instructions.

Fix typo in build instructions

---

src/thread/PosixCond.hxx
src/thread/PosixMutex.hxx

Apparently on hurd-i386 __GLIBC__ is defined, but the pthread
implementation is special and cannot be used with constexpr. Hence
exclude __gnu_hurd__.

fix compilation errors on Debian GNU/Hurd

---

src/mixer/plugins/volume_mapping.c

fixes #362 
ensure that valid mixer values are set also when the ALSA driver
does not report a valid dB range ('set_raw' fallback)
correct a bug in which volume is assumed to lie in [0..100]
instead of [0..1]

clamp 'set_normalized_volume' to valid values also for ALSA softvol

---

test/meson.build

test/run_storage.cxx depends on EventThread/EventLoop from libevent.a.
Depend on it explicitly. This addresses build failure with
-Dtest=true -Dcurl=disabled -Ddbus=disabled

test/meson.build: run_storage depends on event lib

---

src/system/EventPipe.cxx

This is similar to https://github.com/MusicPlayerDaemon/MPD/commit/b177bffa6a5f1b69639b6cd759dcb16fdd76e5e2, in that it fixes the Windows issue of connecting to the open socket. Also, the `listen_socket` is set to `AcceptNonBlock` [after the connection](https://github.com/MusicPlayerDaemon/MPD/blob/98f92d828a72d5ce984d2d4ae2193a4533b280e5/src/system/EventPipe.cxx#L123) anyways.
This seems to fix #343

remove non-block call

---

src/zeroconf/meson.build

The `-framework` linker argument is unavailable on non-darwin platforms, leading to linker errors, e.g. with LLD. On other platforms the default link argument `-ldns_sd` works fine, though.

Fix link_args for mDNSResponder on non-darwin platforms

---

doc/plugins.rst
src/output/plugins/ShoutOutputPlugin.cxx

Adds an optional config option for the "shout" output to support use of libshout's `shout_set_tls` functionality. Defaults to "disabled", which is the same as the behavior before this patch: no attempt at TLS will be made.
To use with icecast, set `<ssl>1</ssl>` on a listen socket in the icecast configuration. When testing, I was successful in getting it to work using "auto", "auto_no_plain" and "rfc2818" modes with the [icecast 2.5 beta](https://ftp.osuosl.org/pub/xiph/releases/icecast/icecast-2.5-beta2.tar.gz). I also tested with icecast 2.4.3 with the same config but couldn't get any of the TLS modes to work.
[This Xiph wiki page](https://wiki.xiph.org/Icecast_Server/known_https_restrictions) seems to claim that TLS should work since icecast 2.4.1 but also that icecast 2.5 contains a …

shout output plugin: add support for TLS

---

src/output/plugins/OSXOutputPlugin.cxx

Currently it falls back to system default device (either internal speaker or headphone) when device not found. 
I believe it is a better to fail in this case, to make it better aligned with platforms (such as alsa).

[OSXOutput] Throw an error when device not found

---

doc/protocol.rst

* "`lsinfo`" argument is optional
* "`tagtypes disable`" arguments are mandatory (typo)

Fixed protocol documentation

---

src/lib/cdio/Paranoia.hxx

Ensure SEEK_SET is set on systems where stdio.h is not pulled in by accident.

Ensure SEEK_SET is defined.

---

doc/protocol.rst
src/command/PlaylistCommands.cxx
src/playlist/PlaylistAny.cxx
src/playlist/PlaylistAny.hxx
src/playlist/PlaylistQueue.cxx
src/playlist/PlaylistQueue.hxx
src/playlist/Print.cxx
src/playlist/Print.hxx

Adresses #455.
Before this patch, 
```
load /foo/bar.m3u
```
always fails with `ACK [50@0] {load} No such playlist`
With this patch we have
- remote clients: always fails with `ACK [4@0] {} Access denied`
- local clients:
- success `OK` if the files exists
- otherwise fails `ACK [52@0] {} Failed to access /foo/bar.m3u: No such file or directory`.
Behaviour for relative paths and remote URI is not changed.

Allow local clients to load playlists in arbitrary absolute location

---

doc/plugins.rst
src/decoder/plugins/PcmDecoderPlugin.cxx
src/input/plugins/AlsaInputPlugin.cxx

Extend the alsa:// input scheme to allow users to select an audio format to use by specifying it in a query component on the URI.
Also allows admins to override the built-in defaults for device name and audio format using mpd.conf settings.

Alsa input plugin

---

src/lib/ffmpeg/Filter.hxx

add missing header.

---

src/input/InputPlugin.cxx
src/input/InputPlugin.hxx
src/input/plugins/AlsaInputPlugin.cxx
src/input/plugins/CdioParanoiaInputPlugin.cxx
src/input/plugins/CurlInputPlugin.cxx
src/input/plugins/FfmpegInputPlugin.cxx
src/input/plugins/MmsInputPlugin.cxx
src/input/plugins/NfsInputPlugin.cxx
src/input/plugins/QobuzInputPlugin.cxx
src/input/plugins/SmbclientInputPlugin.cxx
src/input/plugins/TidalInputPlugin.cxx
src/ls.cxx

This PR adds support for enumerating input schemas at runtime. Basically, this is needed because FFMPEG libraries can be compiled with different flags and thus may or may not support gopher or rtmp, depending on the user's choice. It's a better solution, IMHO, than hardcoding supported protocols into MPD.

Runtime schema enumeration support

---

doc/plugins.rst
src/decoder/plugins/SidplayDecoderPlugin.cxx

Genres are not part of the SID format, so SID files are genreless. This
"default_genre" option may be used to assign a default genre to all SID
music, for example "SID", "C64", "Chiptune", etc.

decoder/sidplay: Add "default_genre" option

---

src/input/cache/Manager.cxx

This fixes https://github.com/MusicPlayerDaemon/MPD/issues/691
In that issue we found a bug in `InputCacheManager::Get` due to incorrect use of the Boost intrusive::set API. The pair of functions `insert_check`/`insert_commit` allow you to amortize the cost of a tree walk across two function calls. This performance gain comes at the cost of complexity: you may not modify the tree in between `insert_check` and `insert_commit`.
If you do modify the tree, you will get sporadic runtime assertion failures (i.e. crashes). This is the cause of #691.
My gut feeling is that `InputCacheManager::Get` is too complex to use `insert_check` / `insert_commit` correctly. I would have to add comments to remind myself of what is going on, and why things need to happen in just the right order. I also don't …

input/cache: use simpler intrusive::set API

---

src/playlist/PlaylistSong.cxx

This is needed to correctly load playlist entries that reference a song in a cuesheet that is treated as a folder.
Currently, if songs that are part of a cuesheet that is treated as a folder are stored in a playlist and the playlist is loaded the queue is populated with the individual songs according to their metadata but reference the whole audio file referenced by the cuesheet, instead of only the parts that actually belong to the individual songs.
This behavior is fixed with this PR by copying the start and end time over in merge_song_metadata.

playlist/PlaylistSong: also copy start and end time in merge_song_metadata

---

src/archive/plugins/Bzip2ArchivePlugin.cxx
src/archive/plugins/Iso9660ArchivePlugin.cxx
src/db/VHelper.cxx
src/db/VHelper.hxx

Found with modernize-pass-by-value

[clang-tidy] pass by value where appropriate

---

src/CommandLine.cxx
src/LogInit.cxx
src/archive/ArchiveList.cxx
src/db/update/InotifyUpdate.cxx
src/decoder/plugins/FlacDecoderPlugin.cxx
src/decoder/plugins/MikmodDecoderPlugin.cxx
src/input/plugins/CdioParanoiaInputPlugin.cxx
src/output/State.cxx
src/output/plugins/JackOutputPlugin.cxx
src/output/plugins/PulseOutputPlugin.cxx
src/unix/Daemon.cxx

Found with modernize-redundant-void-arg

[clang-tidy] remove pointless void arg

---

src/CommandLine.cxx
src/db/plugins/ProxyDatabasePlugin.cxx
src/event/FullyBufferedSocket.cxx

Found with readability-simplify-boolean-expr

[clang-tidy] simplify boolean expressions

---

src/input/InputPlugin.cxx
src/ls.cxx
src/storage/StorageState.cxx

Found with performance-for-range-copy

[clang-tidy] convert several loops to const auto&

---

src/command/AllCommands.cxx
src/decoder/plugins/MadDecoderPlugin.cxx
src/neighbor/Glue.cxx

Found with modernize-loop-convert

[clang-tidy] convert several loops to range based ones

---

src/player/CrossFade.cxx
src/player/Thread.cxx
src/playlist/plugins/SoundCloudPlaylistPlugin.cxx

Found with modernize-use-bool-literals

[clang-tidy] use bool literals where appropriate

---

src/lib/upnp/ContentDirectoryService.cxx

Found with readability-string-compare

[clang-tidy] use == instead of compare for strings

---

src/db/DatabasePlaylist.cxx
src/pcm/Dop.cxx
src/pcm/Dsd16.cxx
src/pcm/Dsd32.cxx

Found with modernize-avoid-bind

[clang-tidy] replace std::bind with lambdas

---

src/archive/plugins/ZzipArchivePlugin.cxx
src/command/CommandError.cxx
src/command/CommandError.hxx
src/db/plugins/ProxyDatabasePlugin.cxx
src/db/plugins/simple/Directory.cxx
src/db/plugins/simple/Directory.hxx
src/db/plugins/upnp/UpnpDatabasePlugin.cxx
src/input/Error.cxx
src/input/plugins/QobuzInputPlugin.cxx
src/input/plugins/TidalInputPlugin.cxx
src/tag/ApeLoader.cxx
src/tag/ApeLoader.hxx

Found with performance-unnecessary-value-param

[clang-tidy] convert several functions to const &

---

src/config/Data.cxx
src/lib/dbus/UDisks2.cxx
src/neighbor/plugins/UdisksNeighborPlugin.cxx

Found with bugprone-move-forwarding-reference

[clang-tidy] use forward instead of move

---

src/decoder/plugins/AudiofileDecoderPlugin.cxx
src/decoder/plugins/FaadDecoderPlugin.cxx

The rhs evaluates to void *const, not const void*.
Found with misc-misplaced-const

[clang-tidy] remove misplaced const

---

src/command/PlayerCommands.cxx
src/db/plugins/ProxyDatabasePlugin.cxx
src/decoder/plugins/AdPlugDecoderPlugin.cxx
src/decoder/plugins/FluidsynthDecoderPlugin.cxx
src/decoder/plugins/HybridDsdDecoderPlugin.cxx
src/decoder/plugins/MikmodDecoderPlugin.cxx
src/decoder/plugins/SidplayDecoderPlugin.cxx
src/encoder/plugins/FlacEncoderPlugin.cxx
src/encoder/plugins/OpusEncoderPlugin.cxx
src/input/plugins/CdioParanoiaInputPlugin.cxx
src/input/plugins/CurlInputPlugin.cxx
src/lib/curl/Request.cxx
src/lib/icu/CaseFold.cxx
src/output/plugins/AlsaOutputPlugin.cxx
src/output/plugins/AoOutputPlugin.cxx
src/output/plugins/JackOutputPlugin.cxx
src/output/plugins/ShoutOutputPlugin.cxx
src/output/plugins/httpd/HttpdOutputPlugin.cxx
src/storage/plugins/CurlStorage.cxx
src/util/UTF8.cxx

Found with readability-uppercase-literal-suffix

[clang-tidy] change integer prefixes to uppercase

---

src/decoder/plugins/DsdLib.cxx
src/decoder/plugins/DsdiffDecoderPlugin.cxx

Found with readability-redundant-control-flow

[clang-tidy] remove unneeded return

---

src/output/Control.cxx
src/output/Control.hxx
src/output/Filtered.cxx
src/output/Filtered.hxx
src/output/Interface.hxx
src/output/plugins/AlsaOutputPlugin.cxx

Found with readability-const-return-type

remove redundant const qualification

---

src/CommandLine.cxx

Found with readability-avoid-const-params-in-decls

[clang-tidy] remove const in declaration

---

src/decoder/plugins/HybridDsdDecoderPlugin.cxx
src/decoder/plugins/OpusDecoderPlugin.cxx
src/encoder/plugins/OpusEncoderPlugin.cxx

Found with readability-static-definition-in-anonymous-namespace

[clang-tidy] remove static in namespace

---

src/db/Helpers.cxx

Found with modernize-use-using

[clang-tidy] use using instead of typedef

---

src/db/plugins/ProxyDatabasePlugin.cxx

[clang-tidy] use emplace_back

---

src/db/plugins/upnp/Directory.cxx
src/db/plugins/upnp/Object.cxx
src/lib/upnp/ContentDirectoryService.cxx
src/lib/upnp/Device.cxx
src/song/Filter.cxx

Found with modernize-use-equals-default

[clang-tidy] use = default

---

src/CommandLine.cxx
src/command/StickerCommands.cxx
src/encoder/plugins/OpusEncoderPlugin.cxx
src/input/plugins/QobuzClient.cxx
src/lib/dbus/Glue.cxx
src/lib/upnp/ixmlwrap.cxx
src/sticker/SongSticker.cxx

Found with llvm-namespace-comment

[clang-tidy] add ending namespace comments

---

src/input/IcyInputStream.hxx
src/input/ProxyInputStream.hxx
src/storage/CompositeStorage.hxx

Found with clang's -Winconsistent-missing-destructor-override

fix missing overrides

---

src/input/plugins/AlsaInputPlugin.cxx
src/output/plugins/AlsaOutputPlugin.cxx
src/player/Thread.cxx

fix implicit-fallthrough warnings under clang

---

src/ReplayGainGlobal.cxx
src/ReplayGainInfo.cxx
src/Stats.cxx
src/command/PlayerCommands.cxx
src/decoder/Bridge.cxx
src/decoder/plugins/FaadDecoderPlugin.cxx
src/decoder/plugins/MpcdecDecoderPlugin.cxx
src/decoder/plugins/WavpackDecoderPlugin.cxx
src/mixer/plugins/AlsaMixerPlugin.cxx
src/mixer/plugins/SoftwareMixerPlugin.cxx
src/mixer/plugins/WinmmMixerPlugin.cxx
src/mixer/plugins/volume_mapping.c
src/output/plugins/HaikuOutputPlugin.cxx
src/pcm/Mix.cxx
src/player/CrossFade.cxx
src/util/Math.hxx

std::lround is C++11 and requires _GLIBCXX_USE_C99_MATH_TR1 to be
supported. This is not the case with uClibc-ng.

treewide: math fixes

---

src/fs/io/FileOutputStream.cxx

This was done on Windows with Ubuntu 18.04 with clang-11 and more of MPD being compiled.

more clang-tidy

---

src/Stats.cxx
src/command/PlayerCommands.cxx
src/decoder/plugins/FaadDecoderPlugin.cxx
src/mixer/plugins/WinmmMixerPlugin.cxx
src/output/plugins/HaikuOutputPlugin.cxx
src/pcm/PcmMix.cxx
src/player/CrossFade.cxx
src/util/Math.hxx

This is the case with uClibc-ng currently.
(cherry picked from commit 769cd0ee9f0cf8ceb026aa751b5d4a390bb5dbdc)
(changed define to match master)

[0.21.x]treewide: use boost::lround when std::round is unavailable

---

src/CommandLine.cxx
src/system/FatalError.cxx
src/unix/Daemon.cxx
src/util/Alloc.cxx

_exit and std::_Exit are identical, expect the latter is standard C++.
Added several functions to the std namespace as a result of headers.

replace exit and _exit with std variants

---

meson.build
src/Main.cxx

Switch to std:: functions. Changed the meson check. Works locally.

replace locale.h with clocale

---

src/util/Math.hxx

The _GLIBCXX_USE_C99_MATH macro is defined in glibcxx by c++config.h, which
gets included by every header. Which means a header needs to be present.

Math.hxx: move cmath include out of define

---

src/command/FileCommands.cxx
src/input/InputPlugin.cxx
src/lib/nfs/Cancellable.hxx
src/output/MultipleOutputs.cxx
src/output/MultipleOutputs.hxx
src/song/AndSongFilter.cxx
src/tag/Builder.cxx

std::any_of becomes constexpr in C++20. I'm not sure it results in better
performance.
Found with useStlAlgorithm

[cppcheck] convert several functions to use std::any_of

---

src/util/Math.hxx

The _GLIBCXX_USE_C99_MATH macro is defined in glibcxx by c++config.h, which
gets included by every header. Which means a header needs to be present.
(cherry picked from commit 79e9aff3382d8b7521318c44835a6dd6b284e2c1)

[0.21.x]Math.hxx: move cmath include out of define

---

src/output/plugins/SolarisOutputPlugin.cxx

- Use AUDIO_INITINFO rather than AUDIO_GETINFO for initialization
This is recommended by Solaris and NetBSD documentation.
- Support S8 and S32 audio formats.

SolarisOutputPlugin: Various improvements

---

doc/protocol.rst

As per #658, you are actually interested in improvements of the protocol specification. Therefore, I thought you might be interested in documentation this edge case regarding the currentsong response format. 
---
The parser implemented in libmpdclient requires the first key-value pair
of the server response to be the file pair. This is due to the fact that
libmpdclient scan pairs sequentially and first attempts to extract the
file pair before parsing the currentsong response further. See:
https://github.com/MusicPlayerDaemon/libmpdclient/blob/5c751a761ec9f71a43ee0e41cfff3208f31a58b8/src/song.c#L559-L563
Meta data encoded as pairs in the currentsong response will be ignored
if they are placed before the file pair in the response.

doc: Document required order of currentsong response

---

NEWS
doc/plugins.rst
src/decoder/plugins/SidplayDecoderPlugin.cxx

High Voltage SID Collection introduces new song length database. PR adds support for new libsidplayfp 2.0 feature while being compatible to older versions of library and format. No need to convert the database any longer :)

decoder/sidplay: support new song length format with libsidplayfp 2.0

---

src/db/Count.cxx
src/db/DatabasePlaylist.cxx
src/db/DatabasePrint.cxx
src/db/DatabaseQueue.cxx
src/db/Helpers.cxx
src/db/plugins/simple/Mount.cxx
src/decoder/DecoderPrint.cxx
src/decoder/Thread.cxx
src/pcm/Dop.cxx
src/pcm/Dsd16.cxx
src/pcm/Dsd32.cxx

Reduces unstripped size. stripped size is the same.
Also took the time to remove using std::placeholders.

remove std::bind usage as much as possible

---

src/lib/icu/Win32.cxx

This prevent for strange extra char occur after any file path, while MPD tried to create or open any file on my windows 10 computer,
Also, using `std::make_unique` for creating `std::unique_ptr`, but `std::make__unique` is for c++14 and newer, should we prepare for compatibility to c++11?

lib/icu: add null terminate in win32 string and wstring

---

.travis.yml

c++17 is offered by default with Xcode 10
https://developer.apple.com/documentation/xcode_release_notes/xcode_10_release_notes

macos: change CI xcode to 10.3 for c++17 support

---

doc/user.rst

Taken from [here](https://github.com/MusicPlayerDaemon/MPD/commit/09f743dc1a03217186fbb3408bffacee659b442c#diff-b121d9954d5394bce0c50b7cbbb5bd50R422-R428), seems it was lost during conversion from DocBook.

doc/user.rst: document include_optional directive

---

doc/plugins.rst

Currently, the hardcoded URL points to a non-existent page.

doc/plugins.rst: use reference to ffmpeg plugin section

---

src/lib/upnp/ContentDirectoryService.cxx
src/net/IPv6Address.hxx

remove GCC5 hacks

---

meson.build
src/Main.cxx

clocale is part of C++11.
In practical terms, gcc's libstdc++ comes with its own locale defines
when the libc does not have them.
Also reworked to be dependent on !ANDROID.

remove clocale test

---

src/storage/CompositeStorage.cxx

Found with performance-move-const-arg

clang-tidy: remove pointless std::move

---

src/io/FileDescriptor.hxx

`dup2` returns `new_fd`, so assuming the intention was for `true` to indicate success, this needs to check for `== new_fd.Get()` or `>= 0` or `!= -1` instead.

system/FileDescriptor: fix Duplicate result

---

src/command/FileCommands.cxx
src/db/plugins/ProxyDatabasePlugin.cxx
src/song/Filter.cxx

Found with readability-use-anyofallof

clang-tidy: convert to all/any_of

---

src/lib/dbus/UDisks2.cxx
src/neighbor/plugins/UdisksNeighborPlugin.cxx
src/storage/plugins/UdisksStorage.cxx

Found with modernize-avoid-bind
Reduces size from
```
29134736
3538352
```
to
```
29067848
3534256
```
compiled without optimization of course.

clang-tidy: replace std::bind with lambdas

---

NEWS
src/command/PartitionCommands.cxx
src/output/Control.cxx
src/output/Control.hxx
src/output/MultipleOutputs.cxx
src/output/MultipleOutputs.hxx

Added mentioned snippets of code #994 .
When moving an output to a partition, the configuration of the AudioOutputControl will be copied as well.
So tags and always_on setting are also copied over to the partition for this output.
This does not resolve the issue with replay_gain not being set to the correct value, this needs to be done in the newpartition command.

Fixes #994 - AudioOutputControl created from copy

---

doc/protocol.rst

When taking a look on the [protocol documentation](https://www.musicpd.org/doc/html/protocol.html) I noticed not all commands have unique html id tags so i couldn't easily link what I wanted to link.
One regex replace and one test build with sphinx later, all :command: thingies have their unique target name now.
Thanks for mpd!

doc/protocol.rst: ensure all commands have targets

---

doc/protocol.rst

The link is called `[#since_0_19]` but the text says `0.20`.
Edit: I also noticed that one of the places the `oneshot` option for `single` was still listed as `0.20` instead of `0.21`.

doc/protocol.rst: fix mistake in footnotes

---

src/storage/plugins/CurlStorage.cxx
src/util/UriExtract.cxx
src/util/UriExtract.hxx

- Removed additional "a:prop" in PROPFIND request to match [RFC 4918 section 9.1.3](https://tools.ietf.org/html/rfc4918#section-9.1.3). (bug)
- Added Content-Type header as the body is not a true multipart POST.
- Fixed parsing propstat so that the correct propstat block is used when extracting relevant property values
- Added support for scheme-less URI in response href
Fixes https://github.com/MusicPlayerDaemon/MPD/issues/1039
The above were needed to make scanning work with Nextcloud which implements Webdav in a stricter way.
Tested against a Nextcloud 20 instance which also contained file names with Chinese characters.
Scanning worked in deeper directory trees and music could be played.
Some of the code might be slightly clumsy as it's my first time with C++11
and due to my struggles …

Fixed Webdav storage scanning to be more RFC compliant

---

doc/plugins.rst
src/encoder/plugins/OpusEncoderPlugin.cxx

* Adds the ability to set `packet_loss` and `vbr` options for the Opus encoder.
* `packet_loss` is especially useful to set when piping Opus encoded audio to a source that relies on UDP / RTP because it can help mitigate any lost or corrupt Opus packets.

add additional opus encoder options

---

src/archive/ArchiveList.cxx
src/db/Registry.cxx
src/db/plugins/simple/SimpleDatabasePlugin.cxx
src/decoder/DecoderList.cxx
src/encoder/EncoderList.cxx
src/filter/Registry.cxx
src/input/Registry.cxx
src/neighbor/Registry.cxx
src/output/Registry.cxx
src/output/plugins/AlsaOutputPlugin.cxx
src/output/plugins/PulseOutputPlugin.cxx
src/playlist/PlaylistRegistry.cxx
src/playlist/plugins/ExtM3uPlaylistPlugin.cxx
src/storage/Registry.cxx
src/storage/plugins/LocalStorage.cxx

Found with cppcoreguidelines-interfaces-global-init

clang-tidy: mark a bunch of variables constexpr

---

src/zeroconf/ZeroconfBonjour.cxx
src/zeroconf/meson.build

The changes for made to ZeroconfBonjour.cxx for "refactor to SocketEvent" didn't actually compile. 
Also I've reenabled bonjour for the darwin build. dnssd is now in the System framework so there is no need for an additional link_arg.

zeroconf/ZeroconfBonjour: Fix compile errors resulting from "refactor to SocketEvent" and reenable bonjour for darwin build

---

doc/plugins.rst
src/input/plugins/CurlInputPlugin.cxx

Add cacert option for curl plugin
add cacert option for Curl plugin. Allows to set cacert for curl lib
Added documentation line into doc/plugins.rst with explanation for cacert option

Add cacert option for Curl plugin. Allows to set cacert for curl lib

---

doc/client.rst

At least I believe libmpdclient is reading env. var. as second:
https://github.com/MusicPlayerDaemon/libmpdclient/blob/master/src/settings.c#L142
ncmpc manual also mentions `MPD_TIMEOUT` being is second.

MPD_TIMEOUT is in seconds

---

doc/plugins.rst
src/decoder/plugins/ModplugDecoderPlugin.cxx

This PR adds the ability to change modplug's resampling mode via mpd.conf.
This is handy when playing modules that are meant to be played without interpolation (many chiptune and Amiga modules).

Add resampling mode setting to modplug decoder

---

doc/plugins.rst
meson_options.txt
python/build/libs.py
src/decoder/DecoderList.cxx
src/decoder/plugins/OpenmptDecoderPlugin.cxx
src/decoder/plugins/OpenmptDecoderPlugin.hxx
src/decoder/plugins/meson.build

This PR adds the OpenMPT decoder plugin, based on libopenmpt.
Before you merge, I have some questions:
What does `python/build/libs.py` do? Is this a Windows thing where it downloads the libraries, or does it also apply to Unix-based systems?
There's a small amount of code re-use:
```cpp
const auto buffer = mod_loadfile(nullptr, is);
if (buffer.IsNull()) {
LogWarning(openmpt_domain, "could not load stream");
return false;
}
openmpt::module mod(buffer.data, buffer.size);
delete[] buffer.data;
```
Is there a way to make a function out of it like how it's done in `ModplugDecoderPlugin.cxx`? When I tried I got into problems with returning `openmpt::module` iirc.
Also, are there any memory leaks or memory-related bugs in my code? I'm not that experienced in C/C++. While developing the OpenMPT …

Add openmpt decoder plugin

---

src/mixer/plugins/OssMixerPlugin.cxx
src/mixer/plugins/SndioMixerPlugin.cxx
src/output/plugins/OssOutputPlugin.cxx
src/output/plugins/SndioOutputPlugin.cxx

Found with cppcoreguidelines-interfaces-global-init

add constexpr

---

doc/plugins.rst

Currently, it issues a warning when documentation is built:
```
WARNING: Unknown target name: "pipewire <https://pipewire.org/>`".
```
and the link is not rendered in the HTML output.

doc/plugins.rst: fix PipeWire link

---

src/Log.hxx
src/lib/expat/ExpatParser.hxx

Fixes
../git/src/Log.hxx:121:42: error: no member named 'forward' in namespace 'std'
LogFormat(LogLevel::ERROR, e, fmt, std::forward<Args>(args)...);
Signed-off-by: Khem Raj <raj.khem@gmail.com>

include <utility> for std::forward

---

src/archive/meson.build

I couldn't compile a recent master (57687779b) on macOS with MacPorts. Adding this Meson depency solved the problem.

archive/meson.build: add missing libfmt dependency

---

src/decoder/plugins/MikmodDecoderPlugin.cxx

Found with cppcoreguidelines-avoid-non-const-global-variables

constexpr global variable conversion

---

src/filter/plugins/ConvertFilterPlugin.cxx
src/tag/Builder.cxx

The latter is easier to read and is the "correct" thing to do.

unique_ptr/new to make_unique

---

src/output/plugins/snapcast/SnapcastOutputPlugin.cxx

Found with readability-use-anyofallof

clang-tidy: replace loop with std::all_of

---

src/playlist/cue/CueParser.cxx

Found with readability-const-return-type

clang-tidy: remove pointless const

---

src/lib/ffmpeg/Interleave.cxx

The type is duplicated otherwise
Found with modernize-use-auto

clang-tidy: use auto

---

doc/user.rst

NB: Check the sysconfdir setting to determine where mpd will look for mpd.conf; if you expect mpd to look for /etc/mpd.conf the sysconfdir must be '/etc' (i.e., not 'etc' which will result in mpd looking for /usr/local/etc/mpd.conf):
.. code-block:: none
meson configure output/release |grep sysconfdir
If this is not /etc (or another path you wish to specify):
.. code-block:: none
$ meson configure output/release -Dsysconfdir='/etc' ; meson configure output/release |grep syscon
sysconfdir              /etc                                               Sysconf data directory

Update user.rst install to include specification of meson sysconfdir

---

doc/plugins.rst
src/db/plugins/upnp/UpnpDatabasePlugin.cxx
src/lib/upnp/ClientInit.cxx
src/lib/upnp/ClientInit.hxx
src/lib/upnp/Init.cxx
src/lib/upnp/Init.hxx
src/neighbor/plugins/UpnpNeighborPlugin.cxx

Add an option to the UPnP database plugin to configure which interface
is used by upnp to discover servers.
upnp by default selects the first interface that is not loopback, which
in some cases might not be the desired interface. For example if wanting
to access a DLNA server over a VPN connection.
The "interface" option can now be set to the name of the desired
interface to achieve this.
The default behaviour remains unchanged.

upnp: add option to configure interface for db plugin

---

src/output/plugins/PipeWireOutputPlugin.cxx

This fixes this build error observed with clang and `-stdlib=libc++`:
```
../mpd-0.23.3/src/output/plugins/PipeWireOutputPlugin.cxx:661:55: error: implicit instantiation of undefined template 'std::array<std::byte, 64>'
std::array<std::byte, MAX_CHANNELS * MAX_INTERLEAVE> buffer;
^
/usr/include/c++/v1/__tuple:219:64: note: template is declared here
template <class _Tp, size_t _Size> struct _LIBCPP_TEMPLATE_VIS array;
^
```

output/plugins: fix build error with clang and -stdlib=libc++

---

src/util/LazyRandomEngine.cxx
src/util/LazyRandomEngine.hxx

Signed-off-by: Shen-Ta Hsieh <ibmibmibm.tw@gmail.com>

util/LazyRandomEngine: use std::optional to avoid allocation

---

src/client/Response.cxx

clang-tidy reports this is trivially copyable and thus std::move has no
effect.

remove std::move

---

doc/conf.py

This enhances readability in sidebar, especially for "User’s Manual" and
"Protocol" pages

doc/conf.py: Set sidebar width to 300px to limit wrapping

---

src/archive/plugins/ZzipArchivePlugin.cxx

use cinttypes header

---

src/net/DscpParser.cxx

Correct value is 0x04 since the lower 2 ECN bits need to be accounted for.

Fix DSCP LE value

---

doc/meson.build
meson_options.txt

Added a `doxygen` option to the `doc` build. It makes use of the already-present but unused file `doxygen.conf.in`. The option is set to false by default.

Add (resurrect?) doxygen support

---

src/lib/icu/meson.build

iconv() integration may fail when libiconv is installed. In that case, the build may silently disable iconv or fail later during build, because -liconv is not specified.
Installation of libiconv hides the functionality provided by the C library (it overwrites usr/include/iconv.h and redefines symbols by redefining them, e.g. #define iconv_open libiconv_open)
Meson iconv() detection may accept a libiconf installation, but fails to provide an automatic dependency. The link stage subsequently fails with:
/nvmedata/autobuild/instance-29/output-1/host/lib/gcc/i686-buildroot-linux-uclibc/9.4.0/../../../../i686-buildroot-linux-uclibc/bin/ld: src/lib/icu/libicu.a.p/Converter.cxx.o: undefined reference to symbol 'libiconv_open'
/nvmedata/autobuild/instance-29/output-1/host/lib/gcc/i686-buildroot-li …

src/lib/icu: fix iconv() detection when libiconv is installed

---

src/decoder/plugins/FfmpegDecoderPlugin.cxx

Seeking HLS on-demand streaming not work if the content is served by a server which doesn't support partial requests from the client for file downloads.
I believe the pertial request support is not really needed because content is split into short length chunk files in HLS streaming.
This situation can be reproduced by following procedure (I'm using x86 PC running Ubuntu 20.04).
Prepare HLS example content as follows:
```
$ mkdir test
$ ffmpeg -i example.flac -vn -c:a aac -b:a 128000 -f hls -hls_list_size 0 test/output.m3u8
```
Prepare NGINX web server using the official Docker image.
```
$ docker run --name tmp-nginx-container -d nginx
$ docker cp tmp-nginx-container:/etc/nginx/conf.d/default.conf .
$ docker rm -f tmp-nginx-container
```
Edit default.conf and add "max_ranges 0;" to …

Fix seeking HLS on-demand streaming not working

---

.github/ISSUE_TEMPLATE/bug_report.md

I saw #1560 and felt that the need for the inclusion of a backtrace could be expressed directly in the issue template, which is the first document that new bug reporters will see.

.github: Add reminder to include backtrace in issue template

---

src/playlist/cue/CueParser.cxx
src/playlist/plugins/EmbeddedCuePlaylistPlugin.cxx

No need for C pointer manipulation.
Removed data() for string_view as [] can be used without.
That assert looks like it should be
```
assert(src.back() == '"');
```
Unless I understand the code wrong.

use data() instead of &[0]

---

doc/plugins.rst
src/input/plugins/CurlInputPlugin.cxx
src/lib/curl/Request.hxx
src/lib/curl/Setup.cxx

Enables the user to override the hard coded 10 seconds curl connection timeout.

Added connect_time configuration to curl input plugin

---

doc/plugins.rst
src/input/plugins/CurlInputPlugin.cxx

Use of these options can help diagnose network streaming issues or work around network interruptions and server dropped connections.

curl input plugin - added config options: verbose, low_speed_limit, low_speed_time, tcp_keepalive, tcp_keepidle, tcp_keepintvl

---

src/tag/Builder.cxx
src/tag/Tag.cxx

Especially `Tag::Clear()` avoiding `tag_pool_lock` has a noticeable effect on performance.

In Tag and TagBuild: skip unnecessary code when num_items is 0

---

doc/_static/css/custom.css
doc/conf.py
doc/meson.build

Followed [this sphinx doc](https://docs.readthedocs.io/en/stable/guides/adding-custom-css.html#adding-custom-css-or-javascript-to-sphinx-documentation) to add a custom css.
It overrides text alignment to left instead of justified, and hyphenation to manual instead of auto.
Seems to be more readable this way without words getting broken by an hyphen.

Docs: added custom.css to override default hyphenation and text alignment

---

systemd/user/mpd.service.in

ProtectSystem= and other sandboxing options require a user namespace in order to work as user units (the user manager does not run as root and thus without a user namespace it is unable to perform mounts).
We are looking to enable this implicitly. Very few user units use these options, so want to make sure it is intentional and won't cause regressions. The alternative is to remove ProtectSystem=.

systemd: use PrivateUsers= in user unit

---

src/playlist/PlaylistQueue.cxx

This PR updates `playlist_check_load_song()` to log a message (at level warn) on error to address [issue 1546](https://github.com/MusicPlayerDaemon/MPD/issues/1546)

Address issue #1546

---

doc/protocol.rst
src/tag/Fallback.hxx

Unlike album, artist and albumartist, title and composer were not used as a fallback when titlesort and composersort were specified but unavailable - this patch fixes that.

Allow titlesort and composersort to fall back to title and composer

---

doc/user.rst

/proc/config.gz is not present on all Linux systems. Following the information listed on
https://superuser.com/questions/287371/obtain-kernel-config-from-currently-running-linux-system/287372#287372
added additional grep checks

Provide alternative checks for CONFIG_RT_GROUP_SCHED

---

python/build/libs.py
win32/build.py

I added the required entry to libs.py for libsamplerate and added it to the build script third party lib list.
That way, Windows user can use libsamplerate in addition to the internal resampler.
Tested the resulting python scripts myself on Debian 11 (bullseye), managed to compile mpd.exe without issue.

Adding libsamplerate 0.2.2 to the win32 build & libs.py scripts

---

src/output/plugins/PipeWireOutputPlugin.cxx

Fixes https://github.com/MusicPlayerDaemon/MPD/issues/1753, see https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/3062#note_1805001

output/PipeWire: lock thread loop in SendTag

---

src/output/plugins/httpd/IcyMetaDataServer.cxx

Since using libfmt (commit: dfc5b49) ICY MetaData was broken. Eg MP3 streams encoded with LAME were affected resulting in missing stream titles on VLC or strange noises on Sonos hardware. This commit fixes the icy-metaint field.

output/httpd: fix libfmt icy-metaint replacement field

---

systemd/system/meson.build
systemd/user/meson.build

See https://www.bassi.io/articles/2018/03/15/pkg-config-and-paths/, and https://github.com/ibus/ibus/pull/2388 for a previous instance of this.
Fixes the build in nixpkgs. Without this patch, the build fails because MPD tries to install its unit files in `/nix/store/...-systemd/etc/systemd/system` instead of `/nix/store/...-mpd/etc/systemd/system`.

meson: use correct prefix for systemd dirs

---

doc/user.rst
src/output/Control.cxx
src/output/Control.hxx
src/output/MultipleOutputs.cxx

Add an `always_off` option to outputs that causes them to never start playback even if they're enabled.
This allows placeholder `null` outputs to be defined for the purpose of having an external client react to the enabled state without the side effects of real outputs. Like an external mixer, the client can perform some action when an output is enabled.
Normally `null` outputs can be used for playback so it's possible for MPD to continue playback silently if a problem occurs with all the real outputs (or there are none enabled).

output/Control: Support `always_off` outputs that are never used for playback

---

doc/user.rst

Currently running `meson . output/release --buildtype=debugoptimized -Db_ndebug=true` will issue a warning:
> Running the setup command as `meson [options]` instead of `meson setup [options]` is ambiguous and deprecated.
The [implicit setup](https://mesonbuild.com/Commands.html#setup) command is deprecated since 0.64.0.

doc/user.rst: use explicit meson setup command

---

doc/plugins.rst

These settings are used here: https://github.com/MusicPlayerDaemon/MPD/blob/9bb67ae7f0a79494c9aa02e48c8a855bd696c519/src/output/plugins/httpd/HttpdOutputPlugin.cxx#L33-L35

doc/plugins.rst: document missing `httpd` settings

---

src/queue/PlaylistState.cxx

Consume and single oneshot should be saved as string.
closes #1853

Save consume and single oneshot as string

---

src/SongPrint.cxx
src/SongSave.cxx
src/command/DatabaseCommands.cxx
src/command/QueueCommands.cxx
src/db/VHelper.cxx
src/db/plugins/simple/Song.cxx
src/db/plugins/simple/Song.hxx
src/db/update/UpdateSong.cxx
src/playlist/PlaylistSong.cxx
src/queue/PlaylistUpdate.cxx
src/queue/Print.cxx
src/song/DetachedSong.cxx
src/song/DetachedSong.hxx
src/song/Filter.hxx
src/song/LightSong.hxx

addedtime is only set to mtime, if a new song is added to the database.
Code for proxy plugin is missing, this needs a patch for libmpdclient.
closes #378

Add "added" timestamp to song database

---

src/input/plugins/AlsaInputPlugin.cxx

snd_pcm_poll_descriptors_revents() may return any error code; the ALSA docs do not constrain the permitted values. A 'hw' device will only ever return an error if the pfd array passed in is invalid (-EINVAL), but other I/O plugins may return arbitary errors. For example a network-based device may return -EPIPE etc. The resulting exception thrown by
AlsaNonBlockPcm::DispatchSockets() must be caught to prevent the mpd process from being aborted.

input/plugins/Alsa: catch all exceptions

---

build/pkg-config.sh

This allows it to be found on macOS and should fix linking libnfs with builds of the Android app

build: Remove absolute path on pkg-config

---

subprojects/packagefiles/id3tag/meson.build

According to the Makefile.am from libid3 only i3dtag.h should be installed to the include directory. include_HEADERS =	id3tag.h

subprojects: properly export id3tag include headers

---

doc/protocol.rst

The `Time` song tag [starts with an uppercase letter](https://github.com/MusicPlayerDaemon/MPD/blob/a4c7041561fe9215a27dcb4e15bc40d1e48ef59e/src/SongPrint.cxx#L90).

doc/protocol.rst: fix time tag case

---

android/app/build.gradle.kts
android/app/src/main/java/org/musicpd/Receiver.java

Not really sure why but the boot change got stepped on by the other pr. 
Also fixes the jvm target since they changed the naming scheme there.

android: build fixes for recent merges

---

src/decoder/plugins/SndfileDecoderPlugin.cxx

error: non-constant-expression cannot be narrowed from type 'sf_count_t' (aka 'long long') to 'size_type' (aka 'unsigned int') in initializer list
[-Wc++11-narrowing]
215 |                      std::span{buffer, num_frames * frame_size},
|                                        ^~~~~~~~~~~~~~~~~~~~~~~
note: insert an explicit cast to silence this issue
215 |                      std::span{buffer, num_frames * frame_size},
|                                        ^~~~~~~~~~~~~~~~~~~~~~~
|                                        static_cast<size_type>()

sndfile: fix compilation with clang's libc++

---

doc/protocol.rst

The commands in the example currently result in `ACK_ERROR_ARG`.

doc/protocol.rst: update failure response example

---

NEWS

Change introduced in 6913148d99.
Just noticed this change trying to build a debian package, documenting this is nice for downstream to save cycles :)

Add NEWS entry about the switch to sphinx_rtd_theme

---

src/Main.cxx

Playlist will throw an exception if we call next or previous track when it is not in the "playing" state

android: Check playlist state before changing track

---

android/build.py
android/meson.build
doc/user.rst

The `android` command was depricated and has been removed from new installs of the sdk
The license file existing is about all that is stable between different sdk versions and cli vs Android studio installs.
This also bumps the SDK version used to build the bridge header to 34 since we're already using that to build the app and  Github actions doesn't include 29 by default anymore.

android: Github actions build fixes.

---

src/CommandLine.cxx

I believe this is a typo since all other sections have the form "<Singular> plugins", e.g. "Encoder plugins".

CommandLine: fix typo

---

NEWS
doc/protocol.rst
meson.build
src/command/AllCommands.cxx
src/command/PlaylistCommands.cxx
src/command/PlaylistCommands.hxx
src/playlist/Length.cxx
src/playlist/Length.hxx

Count the number of songs and their total playtime in the playlist.

New command countplaylist

---

NEWS
doc/protocol.rst
src/command/StickerCommands.cxx
src/sticker/Database.cxx
src/sticker/Database.hxx
src/sticker/Match.hxx
src/sticker/SongSticker.cxx
src/sticker/SongSticker.hxx

This is an enhanced version of #1885

"sticker find" support for sort and window parameter and handling for integer values

---

src/input/plugins/CdioParanoiaInputPlugin.cxx

This PR tries to address some CDDA playback issues.
**Changes:**
1. Moved speed adjutment after `cdio_cddap_open` as done in cd-paranoia (this seems to prevent errors on speed adjustment)
2. Use sector functions from libcdio-paranoia (`cdio_cddap_*`) to detect sectors (this seems to increase the robustness on special cases like hidden tracks or multisession CDs)
3. Added checks for errors on lsns and non audio tracks
**Improvments:**
* playback of hidden audio tracks (track 0) if present
* complete playback of last track on cd-extra CDs (multisession CDs)
* skipping of tracks on errors like no hidden track, out of range (> num-tracks) or non audio tracks

Extend robustness of cdda playback

---

src/output/plugins/AlsaOutputPlugin.cxx

output/alsa: handle recoverable errors in DrainInternal()

---

android/app/src/main/java/org/musicpd/Main.java

For some reason the type annotations here show @NonNull but that is actually false according to the documentation under service.
This may be null if the service is being restarted after its process has gone away, and it had previously returned anything except START_STICKY_COMPATIBILITY.

android: null check intent in onStartCommand

---

doc/user.rst

Build dep on pkconf is not explicitly needed because other dependencies pull pkconf indirectly (ie libid3tag0-dev), but explicit declaration of a direct MPD build dep is better IMHO.

doc: debian build, add pkconf build dep.

---

src/lib/ffmpeg/LibFmt.hxx
src/lib/fmt/AudioFormatFormatter.hxx
src/lib/fmt/ExceptionFormatter.hxx
src/lib/fmt/PathFormatter.hxx

Upstream libfmt commit fmtlib/fmt@d707292
now requires the format function to be const.
Adjust the function prototype so it is const and can compile.
- fixes #2068 
tested with both libfmt-10.2.1 and libfmt-11.0.0

lib/fmt: support build with libfmt-11.0.0

---

meson.build

Fix bin install location on linux.
For Linux, Meson's default value for bindir is 'bin' [1].
This commit restores mpd's previous functionality of installation in ${prefix}/bin.
[1] https://mesonbuild.com/Builtin-options.html
Fixes #2043

Fix bin install location on linux

---

src/decoder/plugins/Mpg123DecoderPlugin.cxx

For certain mp3 streams mpg123 is unable to calculate the duration of a song resulting in `0:00`. If the size of the stream is known we can pass that to mpg123.  
The line:
https://github.com/MusicPlayerDaemon/MPD/blob/f7790430a0323eadaaa8e0dacce24dda7331d583/src/decoder/plugins/Mpg123DecoderPlugin.cxx#L250 still (correctly) overrides the duration if is has the the right information.
[Documentation for mpg123_set_filesize](https://www.mpg123.de/api/group__mpg123__status.shtml#gad0301e80dbc3f48e47e27d39cd328755)
> Override the value for file size in bytes. Useful for getting sensible track length values in feed mode or for HTTP streams.

Determine mp3 duration on stream size if size unknown.

---

src/song/Filter.cxx

Previously, `AND` expressions were the only filters which used `++s` instead of `s = StripLeft(s + 1)` making them sensitive to spacing issues. This caused nested AND expressions (like e.g. `(((A) AND (B)) AND (C))`) to needlessly be rejected with the following error message: `{find} Word expected` due to the fact that the inner AND expression would leave the cursor `s` at a space rather than the beginning of the next word (remainder was ` AND (C))` rather than `AND (C)`).
This commit fixes this by consistently using `s = StripLeft(s + 1)` instead of `++s` when parsing AND expressions. Although it is not strictly necessary to resolve the AND nesting bug, the case of trivial AND expressions (consisting basically of only superfluous parentheses) is also changed to the new handling. This …

song/Filter: Fix spacing error on nested AND

---

doc/protocol.rst
src/command/AllCommands.cxx
src/command/PlaylistCommands.cxx

Old: searchplaylist {NAME} {FILTER} [{START:END}]
New: searchplaylist {NAME} {FILTER} [window {START:END}]
This is more similar to the other search commands and we can reuse search specific functions in libmpdclient.

Change the semantic of the searchplaylist protocol command

---

NEWS
doc/protocol.rst
src/TagPrint.cxx
src/TagPrint.hxx
src/command/ClientCommands.cxx

Shows the list of tag types configured by the ``metadata_to_use`` setting.

New command tagtypes available

---

NEWS
src/playlist/Print.cxx

For simple listing this can be done by the client, but for the search case the client can not determine the correct position.
I hope this does not break existing client implementations.

Print positions in the search playlist function

---

doc/protocol.rst
src/command/PlayerCommands.cxx
src/playlist/PlaylistQueue.cxx
src/queue/Playlist.hxx
src/queue/PlaylistState.cxx
src/queue/Queue.cxx
src/queue/Queue.hxx

Stores the last loaded playlist uri in the queue struct. Last loaded playlist is set on load command and cleared with the clear command. The last loaded playlist is printed in the status command and saved / restored from the partition state file.
Resolves issue #938

Store last loaded playlist

---

NEWS
doc/protocol.rst
meson.build
src/client/Client.hxx
src/client/ProtocolFeature.cxx
src/client/ProtocolFeature.hxx
src/command/AllCommands.cxx
src/command/ClientCommands.cxx
src/command/ClientCommands.hxx
src/command/OtherCommands.cxx

This commit adds a new protocol command to toggle protocol features for a client connection. It works like the tag_mask and the associated tagtypes command.
New commands:
- protocol
Shows enabled protocol features.
- protocol available
Show all available protocol features.
- protocol enable {feature...}
Enables protocol features.
- protocol disable {feature...}
Disables protocol features.
- protocol all
Enables all available protocol features.
- protocol clear
Disables all protocol features.
This commit adds also the first protocol feature.
hide_playlists_in_root
Disables the listing of playlists in the root folder for the lsinfo command.

New protocol command to toggle protocol features

---

src/lib/icu/meson.build

ICU 76 decided to reduce overlinking[^1] thus `icu-i18n` will no longer add `icu-uc` when linking to shared libraries. This results in failure:
```
src/lib/icu/libicu.a.p/Converter.cxx.o: undefined reference to symbol 'ucnv_fromUnicode_76'
```
---
ICU 76:
```console
$ objdump -p libicui18n.so | grep icuuc
NEEDED               libicuuc.so.76
$ pkg-config --libs-only-l icu-i18n
-licui18n
$ pkg-config --libs-only-l --static icu-i18n
-licui18n -licuuc -licudata -lpthread -lm
$ pkg-config --libs-only-l icu-i18n icu-uc
-licui18n -licuuc
```
ICU 75
```console
$ objdump -p libicui18n.so | grep icuuc
NEEDED               libicuuc.so.75
$ pkg-config --libs-only-l icu-i18n
-licui18n -licuuc -licudata
$ pkg-config --libs-only-l --static icu-i18n
-licui18n -licuuc -licudata -lpthread -lm
$ pkg-config …
```

meson.build: support building with ICU 76

---

NEWS
doc/protocol.rst
src/command/ClientCommands.cxx

This subcommand combines "clear" and "enable" in one command.

Add "reset" subcommand to tagtypes.

---

src/output/Source.cxx

Close the filter before cancelling when closing a source. Fixes #2148

output/Source: fix Close()

---

NEWS
doc/protocol.rst
src/command/StickerCommands.cxx
src/sticker/Database.cxx
src/sticker/Database.hxx
src/sticker/SongSticker.cxx
src/sticker/SongSticker.hxx

Let sqlite do the work for incrementing or decrementing a sticker value. This sub-commands are usefull to track playcounts with sticker values and saves us one roundtrip.

Add sticker sub-commands inc and dec

---

src/decoder/plugins/meson.build

Incorrect not FMT_STRING change was included in the #2181 change. Revert that line.

plugins/meson.build: revert unintentional static link change

---

src/command/FingerprintCommands.cxx
src/command/NeighborCommands.cxx
src/output/plugins/PipeWireOutputPlugin.cxx

Fixes: 9db7144d0fa4512335070a984690f3f5034210a5
Still had build failures with a more maximalist build. So I grepped for other uses and removed them.
I didn't remove use from src/lib/icu/Converter.cxx as it was correct.

lib/fmt: remove the rest of the broken use of FMT_STRING

---

python/build/libs.py

https://boostorg.jfrog.io no longer works, replacing with url linked by Boost project itself.

python/build/libs.py: replace broken Boost 1.81.0 url

---

subprojects/packagefiles/id3tag/meson.build

Fixes `ERROR: Invalid source tree: first statement must be a call to project()`, and missing comma in `libid3tag_dep` definition.

subprojects/packagefiles/id3tag/meson.build: fix meson errors

---

doc/user.rst

Since 0.23.17 it's no longer possible to cross compile for Windows on Linux using win32/build.py with meson 0.56.0 due to subprojects like id3tag utilizing meson features not available in 0.56.0.

doc/user: update windows build meson version

---

src/input/meson.build

I don't really know why this does compile on Linux but not on macOS, but regardless, this fixes it. Needed for the `nfsc/libnfs-raw-nfs.h` include in `input/Error.cxx`.

Fix macOS build with nfs enabled

---

doc/user.rst
src/config/File.cxx

This allows resetting bind_to_address to override the default value in a
included config.

config/File: support resetting repeatable params

---

doc/mpd.conf.5.rst
doc/mpdconf.example
doc/user.rst
src/config/Net.cxx
src/config/Path.cxx

This pull request tries to address issues #263 and #476.
With these changes you can use $HOME and some of the $XDG variables directly in the MPD configuration file. I used the functions in "fs/glue/StandardDirectory.hxx" to extract the XDG variables, so currently it's limited to:
- XDG_CONFIG_HOME
- XDG_MUSIC_DIR
- XDG_CACHE_HOME
- XDG_RUNTIME_DIR

Initial support for $HOME and some XDG variables inside the configuration file

---

doc/user.rst

This PR adds an additional bullet point to the existing documentation on the "Failed to initialize io_uring" message, covering the "Permission denied" form of the failure message which is usually caused by SELinux blocking MPD's access to the facility.

Document SELinux-blocked io_uring failures

---

src/apple/ErrorRef.hxx

A trivial fix. While Apple documentation does not say when `CFErrorDomain` was added, as a matter of fact it is undefined on some macOS versions.
```
FAILED: src/apple/libapple.a.p/Throw.cxx.o 
/opt/local/bin/g++-mp-14 -Isrc/apple/libapple.a.p -Isrc/apple -I../mpd-0.24/src/apple -Isrc -I../mpd-0.24/src -I. -I../mpd-0.24 -I/opt/local/libexec/boost/1.76/include -I/opt/local/include -fdiagnostics-color=always -D_GLIBCXX_ASSERTIONS=1 -Wall -Winvalid-pch -Wextra -Wpedantic -std=c++20 -O0 -g -ffast-math -ftree-vectorize -Wcast-qual -Wdouble-promotion -Wmissing-declarations -Wshadow -Wunused -Wvla -Wwrite-strings -Wno-stringop-overflow -fno-threadsafe-statics -fmerge-all-constants -Wcomma-subscript -Wextra-semi -Wmismatched-tags -Woverloaded-virtual -Wsign-promo -Wsuggest-override -Wvolatile …
```

apple/ErrorRef.hxx: define CFErrorDomain if undefined

---

src/client/Process.cxx
src/command/ClientCommands.cxx

protcol -> protocol
comand -> command
Found by Debian's lintian spellchecker

Fix typos in messages

---

NEWS
doc/protocol.rst
meson.build
src/client/Client.hxx
src/client/StringNormalization.cxx
src/client/StringNormalization.hxx
src/command/AllCommands.cxx
src/command/ClientCommands.cxx
src/command/ClientCommands.hxx
src/command/DatabaseCommands.cxx
src/command/QueueCommands.cxx
src/lib/icu/Canonicalize.cxx
src/lib/icu/Canonicalize.hxx
src/lib/icu/Compare.cxx
src/lib/icu/Compare.hxx
src/song/Filter.cxx
src/song/Filter.hxx
src/song/StringFilter.cxx
src/song/StringFilter.hxx
test/TestStringFilter.cxx
test/TestTagSongFilter.cxx

Attempt to implement https://github.com/MusicPlayerDaemon/MPD/issues/2327
* Introduces new `stringnormalization` protocol command
* Implements first string normalization to strip diacritics when using `search` and the related commands
The implementation works, but I am unsure whether I took the right approach (and its my first go at CPP). The threading through of booleans is also getting pretty gnarly in there. So I am mostly looking for feedback at this point. We can also workshop the `stringnormalization` name.

Implement diacritics stripping and string normalization command
